# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: story2audio.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'story2audio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11story2audio.proto\"\"\n\x0cStoryRequest\x12\x12\n\nstory_text\x18\x01 \x01(\t\"C\n\rAudioResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\taudio_url\x18\x03 \x01(\t2=\n\x0bStory2Audio\x12.\n\rGenerateAudio\x12\r.StoryRequest\x1a\x0e.AudioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'story2audio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STORYREQUEST']._serialized_start=21
  _globals['_STORYREQUEST']._serialized_end=55
  _globals['_AUDIORESPONSE']._serialized_start=57
  _globals['_AUDIORESPONSE']._serialized_end=124
  _globals['_STORY2AUDIO']._serialized_start=126
  _globals['_STORY2AUDIO']._serialized_end=187
# @@protoc_insertion_point(module_scope)
